<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Temporalio.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StoreOrders.Domain\StoreOrders.Domain.csproj" />
    <ProjectReference Include="..\StoreOrders.Infrastructure\StoreOrders.Infrastructure.csproj" />
    <ProjectReference Include="..\StoreOrders.Workflows\StoreOrders.Workflows.csproj" />
  </ItemGroup>

</Project>


