// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreOrders.Infrastructure.Persistence;

#nullable disable

namespace StoreOrders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StoreOrdersDbContext))]
    [Migration("20260807161914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreOrders.Domain.Entities.InventoryReservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReservationId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryReservations_OperationKey");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryReservations_OrderItemId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InventoryReservations_Status");

                    b.ToTable("InventoryReservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryReservations_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_InventoryReservations_Status", "[Status] IN ('Active','Released','Consumed')");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.InventoryStock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("ProductId");

                    b.ToTable("InventoryStocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryStocks_AvailableQuantity", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CK_InventoryStocks_ReservedQuantity", "[ReservedQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailableQuantity = 5,
                            ReservedQuantity = 0,
                            RowVersion = new byte[0],
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 2,
                            AvailableQuantity = 20,
                            ReservedQuantity = 0,
                            RowVersion = new byte[0],
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 3,
                            AvailableQuantity = 8,
                            ReservedQuantity = 0,
                            RowVersion = new byte[0],
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TemporalWorkflowId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_ClientRequestId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_OrderNumber");

                    b.HasIndex("TemporalWorkflowId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_TemporalWorkflowId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_Status_CreatedAtUtc");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Currency", "LEN([Currency]) = 3");

                            t.HasCheckConstraint("CK_Orders_Status", "[Status] IN ('Received','AwaitingPayment','Paid','Preparing','ReadyForShipment','Shipped','Delivered','Cancelled','Rejected')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount", "[TotalAmount] > 0");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderAddress", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressVersion")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("OrderId");

                    b.ToTable("OrderAddresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderAddresses_AddressVersion", "[AddressVersion] > 0");

                            t.HasCheckConstraint("CK_OrderAddresses_CountryCode", "LEN([CountryCode]) = 2");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderFulfillment", b =>
                {
                    b.Property<Guid>("FulfillmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OperationKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PackedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PackedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FulfillmentId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderFulfillments_OperationKey")
                        .HasFilter("[OperationKey] IS NOT NULL");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderFulfillments_OrderId");

                    b.ToTable("OrderFulfillments", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderFulfillments_Status", "[Status] IN ('Pending','Preparing','Packed','Cancelled')");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderHistoryEntry", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("HistoryId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderHistory_OperationKey");

                    b.HasIndex("OrderId", "OccurredAtUtc")
                        .HasDatabaseName("IX_OrderHistory_OrderId_OccurredAtUtc");

                    b.ToTable("OrderHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderHistory_ActorType", "[ActorType] IN ('System','Customer','PaymentService','Warehouse','DeliveryService')");

                            t.HasCheckConstraint("CK_OrderHistory_CurrentStatus", "[CurrentStatus] IN ('Received','AwaitingPayment','Paid','Preparing','ReadyForShipment','Shipped','Delivered','Cancelled','Rejected')");

                            t.HasCheckConstraint("CK_OrderHistory_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] IN ('Received','AwaitingPayment','Paid','Preparing','ReadyForShipment','Shipped','Delivered','Cancelled','Rejected')");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItems_ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderItems_OrderId_ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_LineTotal", "[LineTotal] >= 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice", "[UnitPrice] >= 0");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("ExternalPaymentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ExternalPaymentReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_ExternalPaymentReference");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_OperationKey");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_OrderId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Currency", "LEN([Currency]) = 3");

                            t.HasCheckConstraint("CK_Payments_Status", "[Status] = 'Confirmed'");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Sku");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_CurrentPrice", "[CurrentPrice] >= 0");

                            t.HasCheckConstraint("CK_Products_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Products_Sku_NotBlank", "LEN(LTRIM(RTRIM([Sku]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 14500.00m,
                            IsActive = true,
                            Name = "Laptop básica",
                            Sku = "LAP-001",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 450.00m,
                            IsActive = true,
                            Name = "Mouse inalámbrico",
                            Sku = "MOU-001",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 3,
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 1200.00m,
                            IsActive = true,
                            Name = "Teclado mecánico",
                            Sku = "KEY-001",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DeliveryWorkflowId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShipmentId");

                    b.HasIndex("DeliveryWorkflowId")
                        .IsUnique()
                        .HasDatabaseName("UX_Shipments_DeliveryWorkflowId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Shipments_OrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Shipments_Status");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Shipments_TrackingNumber")
                        .HasFilter("[TrackingNumber] IS NOT NULL");

                    b.ToTable("Shipments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shipments_Status", "[Status] IN ('Pending','Shipped','Delivered','Cancelled')");
                        });
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.InventoryReservation", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.OrderItem", "OrderItem")
                        .WithOne("InventoryReservation")
                        .HasForeignKey("StoreOrders.Domain.Entities.InventoryReservation", "OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.InventoryStock", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Product", "Product")
                        .WithOne("InventoryStock")
                        .HasForeignKey("StoreOrders.Domain.Entities.InventoryStock", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderAddress", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithOne("Address")
                        .HasForeignKey("StoreOrders.Domain.Entities.OrderAddress", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderFulfillment", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithOne("Fulfillment")
                        .HasForeignKey("StoreOrders.Domain.Entities.OrderFulfillment", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderHistoryEntry", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithMany("History")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StoreOrders.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Payment", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("StoreOrders.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("StoreOrders.Domain.Entities.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("StoreOrders.Domain.Entities.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Order", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Fulfillment");

                    b.Navigation("History");

                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("InventoryReservation");
                });

            modelBuilder.Entity("StoreOrders.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryStock");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
